### ISSUE TITLE
(URGENT) Schemas listing does not respect alphabetical order

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/iso-10303-templates#58]
From:
* metanorma/iso-10303#510

https://github.com/metanorma/iso-10303-templates/blob/cea293b1cc887411c81da3b25e00f00c7bc9da39/resources/_schemas.liquid#L2

The mechanism we use now for `selected` to select schemas in Expressir leads us to always having alphabetical order.

Initially we did not realize that the `schemas.yaml` files need a particular order, e.g.:

`documents/iso-10303-104/schemas.yaml`:
```yaml
schemas:
  structural_response_definition_schema:
    path: ../../schemas/resources/structural_response_definition_schema/structural_response_definition_schema.exp
  structural_response_representation_schema:
    path: ../../schemas/resources/structural_response_representation_schema/structural_response_representation_schema.exp
  finite_element_analysis_control_and_result_schema:
    path: ../../schemas/resources/finite_element_analysis_control_and_result_schema/finite_element_analysis_control_and_result_schema.exp
  fea_scalar_vector_tensor_schema:
    path: ../../schemas/resources/fea_scalar_vector_tensor_schema/fea_scalar_vector_tensor_schema.exp
```

Where this clearly has a specific order of rendering ("f" rendered after "s").

So instead of `selected` being `true` or `false`, we can change to `ordered` that provides a sequential order number and sort it in Liquid after.

This needs to be fixed in both Expressir and also metanorma-plugin-lutaml (I think?).

CC @kwkwan for ideas.
